language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
install:
  - sudo ./setup_apache.sh
  - pip install astroid==1.3.8
  - pip install logilab-common==1.1.0
  - pip install pylint==1.3.1
  - pip install setuptools-lint
script: python setup.py test lint
