language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
install:
  - sudo ./setup_apache.sh
  - pip install astroid==1.3.2
  - pip install logilab-common==0.62.1
  - pip install pylint==1.3.1
  - pip install setuptools-lint
script: python setup.py test lint
